### ISSUE TITLE
infer.py的问题

### ISSUE THREAD

**Issue by blackmail3** [EuphoriaYan/zi2zi-pytorch#10]
更改infer.py中的parser.add_argument('--input_nc', type=int, default=3)后在generator.py中报如下错误：
`RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[13, 1, 256, 256] to have 3 channels, but got 1 channels instead`

**Comment by EuphoriaYan** [comment]
emmm我们当时没怎么用input_nc=3做实验，您可能需要自行修改源代码

**Comment by blackmail3** [comment]
> emmm我们当时没怎么用input_nc=3做实验，您可能需要自行修改源代码

感谢您的回答，那是否将train.py改成input_nc为1后，即可使用infer？

**Comment by EuphoriaYan** [comment]
对的~我们当时因为测试了一下input_nc=3的情况，发现容易出现鬼影或者锯齿边，所以后来就一直用input_nc=1了，infer可能在这基础上写的时候也有些问题

**Comment by blackmail3** [comment]
> 对的~我们当时因为测试了一下input_nc=3的情况，发现容易出现鬼影或者锯齿边，所以后来就一直用input_nc=1了，infer可能在这基础上写的时候也有些问题

emmmmm我直接更改train.py中的input_nc=1后，运行训练会报相同的错误，是和我的obj有关系吗？

**Comment by EuphoriaYan** [comment]
啊对。。。应该使用灰度图，或者您可以直接在dataload的过程中加个convert
