### ISSUE TITLE
package的问题

### ISSUE THREAD

**Issue by blackmail3** [EuphoriaYan/zi2zi-pytorch#11]
不管split_ratio为多少，train.obj都是一个空文件。。。

**Comment by EuphoriaYan** [comment]
可以断点调试一下，看看哪步有问题qwq

**Comment by EuphoriaYan** [comment]
啊不对，您可能需要使用raw_package.py

**Comment by EuphoriaYan** [comment]
那个package.py因为我们项目的原因进行了大幅度改动，您可以使用raw_package.py
