### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by blackmail3** [EuphoriaYan/zi2zi-pytorch#12]
请问预训练模型的源字体和目标字体分别是什么呢？

**Comment by EuphoriaYan** [comment]
源字体是中华书局宋体，charset/ZhongHuaSong里；目标字体是书法家的字，也就是README里的那个writer_dict。

**Comment by blackmail3** [comment]
> 源字体是中华书局宋体，charset/ZhongHuaSong里；目标字体是书法家的字，也就是README里的那个writer_dict。

那请问书法家字体的数据集是根据已有的字体生成的吗。。网上搜这些字体ttf或者otf都找不到www

**Comment by EuphoriaYan** [comment]
书法家字体用的是陈忠建书法库，您可以自行搜索并下载，并且这个程序里用的版本还比较旧了，当时只有28种字体，现在好像超过30种了~
