### ISSUE TITLE
font2imgs img2img

### ISSUE THREAD

**Issue by zijingsh** [EuphoriaYan/zi2zi-pytorch#13]
请问
font2imgs 的src_font  dst_imgs sample_dir

Imgs2Imgs的 src_imgs sample_dir

分别都是什么样的数据  
font2font都运行完成了  a-b  a-c的

**Comment by EuphoriaYan** [comment]
font2imgs是指源图片是一个ttf/otf字体，目标图片是一堆图片的情况，比如你期望用一个字体文件转换风格到一些收集来的书法图片中。imgs2imgs并未加以实现，因为编写代码中，觉得这种训练情况（图片-图片）应该不存在。sample_dir就是采样生成源图片-目标图片对的目录，可以自行指定。

**Comment by zijingsh** [comment]
那么目标图片是以什么为命名呢  是字的编码么 还是什么

**Comment by EuphoriaYan** [comment]
emmm没记错的话是一堆文件夹，每个文件夹名称就是这个文件夹里的字，具体的请看代码解读吧233
