### ISSUE TITLE
about package.py

### ISSUE THREAD

**Issue by XuyangPan** [EuphoriaYan/zi2zi-pytorch#15]
package.py与raw_package.py有什么区别

package.py中的parser.add_argument('--dst_json', type=str, default=None) 的dst_json文件，指的是项目下哪个文件呢

**Comment by EuphoriaYan** [comment]
请使用raw_package.py，package.py里为了我们自己的项目进行了大幅度改动。dst_json是我们在项目过程中，生成的一个包含了大量字体文件数据的json文件。

**Comment by XuyangPan** [comment]
博主，你好，这个项目现在在有使用价值吗

**Comment by EuphoriaYan** [comment]
这个……看你使用场景了呗，sigh
