### ISSUE TITLE
关于生成结果

### ISSUE THREAD

**Issue by caihaunqai** [EuphoriaYan/zi2zi-pytorch#18]
您好，我尝试您给的模型生成，但是结果似乎都是毛笔风格，如果我给的是瘦体/或者是钢笔风格的话，生成很奇怪。 并且请问可以一次输入几个文字一起生成吗？

**Comment by EuphoriaYan** [comment]
可以一次性多字的呀，请仔细阅读README（虽然我感觉我写出来的README一直都很难读）给出的预训练模型是针对毛笔字训练的，所以都是毛笔字；你可以用你自己的训练集去训练钢笔字~
