### ISSUE TITLE
Excuse me, why does the log happen after loading some character style file?

### ISSUE THREAD

**Issue by Ranger-D** [EuphoriaYan/zi2zi-pytorch#20]
![image](https://user-images.githubusercontent.com/52309697/136053744-f4e9628e-127d-4826-a8fa-6f32ebc5557e.png)

**Comment by EuphoriaYan** [comment]
看起来这个img是个None哦，check一下生成的img是否正确（比如显示出来），以及是否读取了正确的字体文件。
It look likes this `img` is None，please check the generating img(for example, show the imgs), and if you load the font file correctly.

**Comment by Ranger-D** [comment]
In my opinion, the problem is caused by font file, because some font files are load correctly and generated img successfully.But why does it happen?

**Comment by EuphoriaYan** [comment]
Maybe your fonts don't contain all the char in charset you selected, so when the program try to generate a nonexistent char, it will return `NoneType`. Check if your charset argument(cjk or txt) is matching with your font file, and you can generate your font file's charset by using `fontTools` lib.
