### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Ranger-D** [EuphoriaYan/zi2zi-pytorch#21]
![cuDNN_error](https://user-images.githubusercontent.com/52309697/136483174-c2b3c35c-ccde-46e0-8a94-1c949da9def3.png)
Excuse me,have you met log like this ? It's really an annoying problem.I have set up required environment, but it didn't work.

**Comment by Note-Liu** [comment]
how did you solve it ?I meet the same problem.Thanks

**Comment by Ranger-D** [comment]
It has been long time and I can't recall clearly.I suggest that you could change tour cudnn version to 10.2
