### ISSUE TITLE
Is it possilble to change image size?

### ISSUE THREAD

**Issue by ApolloZhangCN** [EuphoriaYan/zi2zi-pytorch#22]
Many thanks for your work! I think   the font2img.py  is better thank the original repo.  

Try to use  512*512 ,  can't  train.  is it possible to change the image size ? as my test ,   the only  one which can be put into training  is 256*256 .

thanks!

**Comment by EuphoriaYan** [comment]
Hello! I think you can try the ways below:
1. Resize your picture, use `cv2` or `pillow` lib to resize your pics before input
2. Change the model architecture, such as add one more `conv2d` layer with kernel_size=2, stride=2, in_channel=out_channel=1, or `avgpool2d`/`maxpool2d` layer with kernel_size=2, stride=2 before the generatore network
3. Chaneg the U-net architecture, add one more `UnetSkipConnectionBlock`, or change the discriminator's input component

The degree of difficulty increase progressively.
I hope you can get help~

**Comment by ApolloZhangCN** [comment]
thanks for your quickly reply!
I am not good at DeepLearn, just want to&nbsp; use this repo to creat a handwriting font.&nbsp;
for you advice, the only way I can choose is the No.1,but the real problem is the output image is not clearly when lots of strokes in one character. so I could not do that.
if posssible , could you please update the repo to a flexialbe image size?


thanks in advance!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EuphoriaYan/zi2zi-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EuphoriaYan/zi2zi-pytorch] Is it possilble to change image size? (Issue #22)





 
Hello! I think you can try the ways below:
  
Resize your picture, use cv2 or pillow lib to resize your pics before input
 
Change the model architecture, such as add one more conv2d layer with kernel_size=2, stride=2, in_channel=out_channel=1, or avgpool2d/maxpool2d layer with kernel_size=2, stride=2 before the generatore network
 
Chaneg the U-net architecture, add one more UnetSkipConnectionBlock, or change the discriminator's input component
  
The degree of difficulty increase progressively.
 I hope you can get help~
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EuphoriaYan** [comment]
Sorry for the little design-flexibility , but now I have been graduated from university, worked in compony, so I don't have much time to fix my previous work. 
Also, it's difficult to change the input size into flexible one. As you can see, we use U-net architecture as a generator, so a specific num of `UnetSkipConnectionBlock` layers matches a specific img size. Or we should change both generator and discriminator.
Maybe you can use some img tools in `cv2` lib to polish your img, such as image sharpening.
Sorry again for my sort of mix-up.

**Comment by ApolloZhangCN** [comment]
thanks for your explain.
ok, just let it go . Maybe I need try the DG_Font.

hope everything good for you!
