### ISSUE TITLE
'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by NoMoreBeauty** [EuphoriaYan/zi2zi-pytorch#23]
第一步就报错'NoneType' object has no attribute 'tobytes'
是因为包的版本不匹配嘛

**Comment by EuphoriaYan** [comment]
您好，这个bug，我猜测是没有读取成功图片或者文件……？希望可以将具体的报错行数也一并给出哟~

**Comment by zombieMaybeLikeCake** [comment]
你的src.txt中有出現 --dst_font中沒支援到的字
