### ISSUE TITLE
Where to get the original handwriting caligraphy dataset

### ISSUE THREAD

**Issue by junkaiman** [EuphoriaYan/zi2zi-pytorch#24]
How can I get a copy of the handwriting dataset as shown in the pre-trained data?

Also, may I ask about the training details? How long does it take to get the performance similar to the pre-trained model? And what is the specs? Thanks a lot.

**Comment by EuphoriaYan** [comment]
Hello, all our handwriting dataset are from "陈忠建书法教学资料库", you can find it easily.
It's so long after I finished this repo that I can't remember all the detail. I have a vague view that the training process was on a Titan X, and it takes about a day.

**Comment by junkaiman** [comment]
Thanks💪

**Comment by xunings** [comment]
> Hello, all our handwriting dataset are from "陈忠建书法教学资料库", you can find it easily. It's so long after I finished this repo that I can't remember all the detail. I have a vague view that the training process was on a Titan X, and it takes about a day.

Hi @EuphoriaYan,
Seems that only the per-image data is available in the homepage of "陈忠建书法教学资料库", http://163.20.160.14/~word/modules/myalbum/
Is there any link to download all the fonts as ttf or zip of images?
Thanks in advance.
