### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by huakey** [EuphoriaYan/zi2zi-pytorch#28]
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

求教下，怎么调整？

**Comment by Note-Liu** [comment]
RuntimeError: Given groups=1, weight of size [64, 1, 4, 4], expected input[8, 3, 256, 256] to have 1 channels, but got 3 channels instead.
已经设置--input_nc=1了，还是报错。

**Comment by Note-Liu** [comment]
> RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]
> 
> 求教下，怎么调整？

请问你是怎么解决的
