### ISSUE TITLE
你自己跑的效果怎么样呢？参数设置跟开源的一样么?

### ISSUE THREAD

**Issue by cumthxy** [EuphoriaYan/zi2zi-pytorch#3]
我运行你的开源代码，感觉字体生成的效果不如zi2zi的了。效果不是很好。是我哪里的设置不对么。

我后来又在你的代码基础上增加了vgg loss ，生成的效果也不是很好。
[![Snipaste_2020-09-11_15-10-26.png](https://i.loli.net/2020/09/11/279ouMVyLalGn1E.png)](url)

**Comment by EuphoriaYan** [comment]
这个项目基本上代码就是基于xuan-li的zi2zi-pytorch，然后我把各种loss的权重超参基于原版zi2zi修正了。xuan-li的zi2zi-pytorch网络和原版有变动的是在net_D部分倒数第二层加了个1 x 1的卷积，我测试了一下带或不带这个1 x 1卷积，感觉和原版差距不大；所以我就沿用了这个带1 x 1卷积的，可以加快速度减小模型大小，您可以尝试去掉这个1 x 1卷积试试。
还有一个修改点是我们的数据增强方法是基于Font2Font的，和原版不完全一致，您可以查看一下dataset.py里的DatasetFromObj函数，并尝试修改回原版的数据增强方法。
此外，我们在测试的时候，确实有时候模型会经历“学习”->“崩溃”->"重新学习"这种情况，所以我们目前工作的时候是先生成一堆sample然后看哪个checkpoint的sample最好。暂时我们没时间来修复这个问题，生成效果不佳可能和这个问题也有关系，原作者也说了这网络相当难以训练（哭）。您可以尝试在训练时不只看last_ckpt_sample，也看看别的ckpt的sample，说不定就有哪个ckpt的sample比较好（玄学）

**Comment by Crescentz** [comment]
@cumthxy  @EuphoriaYan  请问你们没有遇到，
1. 图片转二进制时候：缺少.json文件
2. 训练时候output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]
的问题么

**Comment by Crescentz** [comment]
![image](https://user-images.githubusercontent.com/35165563/95591455-e6892400-0a79-11eb-9dcc-729a3ce0e6c6.png)
请问这种是效果好，还是不好，左边是网络自己生成的？ 右边是label？

**Comment by Crescentz** [comment]
![image](https://user-images.githubusercontent.com/35165563/95591531-ff91d500-0a79-11eb-82bd-0cdad20e0d53.png)

**Comment by cumthxy** [comment]
@Crescentz ，你要看细节，而不是在这样范范的对比

**Comment by xueanyi** [comment]
@Crescentz 你好，请问你“形状为[1，256，256]的训练时候输出与广播形状[3，256，256 ]不匹配”这个问题是怎么解决的

**Comment by nissansz** [comment]
最少多少个自己手写字符就可以用来训练模型生成其它字符的手写效果？
