### ISSUE TITLE
开发环境推荐使用导包，这样配置环境比较简单，笔芯

### ISSUE THREAD

**Issue by WindHush** [EuphoriaYan/zi2zi-pytorch#4]
conda env export > environment.yaml	// 导出当前环境的包信息

conda env create -f environment.yaml	// 用配置文件创建新的虚拟环境

pip freeze > piplist.txt	pip freeze > piplist.yaml	// 导出pip安装的所有的包

pip install -r piplist.txt	// 在新的环境中安装导出的包

**Comment by Crescentz** [comment]
请问你们运行 python package.py 没有遇到错误么？
`with open(dst_json, 'r', encoding='utf-8') as fp:
        dst_fonts = json.load(fp)`
没有找到这个字典的任何描述啊

**Comment by EuphoriaYan** [comment]
主要是我这里比较习惯用一个包罗万象的conda环境工作hhh如果导出的话可能有两百多个包，所以就列出了一些核心包~
