### ISSUE TITLE
dst_json

### ISSUE THREAD

**Issue by Crescentz** [EuphoriaYan/zi2zi-pytorch#6]
Traceback (most recent call last):
  File "package.py", line 76, in <module>
    with open(dst_json, 'r', encoding='utf-8') as fp:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Crescentz** [comment]
没有关于dst_json的描述，也没有生成这个文件

**Comment by Crescentz** [comment]
> Traceback (most recent call last):
> File "package.py", line 76, in
> with open(dst_json, 'r', encoding='utf-8') as fp:
> TypeError: expected str, bytes or os.PathLike object, not NoneType

我把作者的ok_fonts那一堆全给注释掉了，可以运行了。不知道有啥后果。

**Comment by EuphoriaYan** [comment]
这是我们当时预处理出来的一个很大的json文件，大致包含了每个字体缺啥字，位置等等内容，您注释掉没影响的
