### ISSUE TITLE
output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

### ISSUE THREAD

**Issue by Crescentz** [EuphoriaYan/zi2zi-pytorch#7]
执行
`ython train.py --experiment_dir=experiment --gpu_ids=cuda:0 --batch_size=32 --epoch=100 --sample_steps=200 --checkpoint_steps=500`

的时候 遇到这个问题

**Comment by Crescentz** [comment]
需要设置--input_nc

**Comment by Crescentz** [comment]
作者大大，README.md没有针对你的文件写啊 /(ㄒoㄒ)/~~

**Comment by blackmail3** [comment]
> 需要设置--input_nc

想问一下infer.py也出现这个问题这样解决不了啊···
